# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formParametres_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogParameters(object):
    def setupUi(self, DialogParameters):
        DialogParameters.setObjectName("DialogParameters")
        DialogParameters.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogParameters.resize(654, 480)
        self.label = QtWidgets.QLabel(DialogParameters)
        self.label.setGeometry(QtCore.QRect(10, 10, 70, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Ressources/parametres.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblTitre = QtWidgets.QLabel(DialogParameters)
        self.lblTitre.setGeometry(QtCore.QRect(90, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitre.setFont(font)
        self.lblTitre.setTextFormat(QtCore.Qt.RichText)
        self.lblTitre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblTitre.setWordWrap(True)
        self.lblTitre.setObjectName("lblTitre")
        self.btnRacine = QtWidgets.QPushButton(DialogParameters)
        self.btnRacine.setGeometry(QtCore.QRect(50, 170, 126, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRacine.sizePolicy().hasHeightForWidth())
        self.btnRacine.setSizePolicy(sizePolicy)
        self.btnRacine.setMinimumSize(QtCore.QSize(75, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Ressources/parcourir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRacine.setIcon(icon)
        self.btnRacine.setIconSize(QtCore.QSize(32, 32))
        self.btnRacine.setObjectName("btnRacine")
        self.lblRacine = QtWidgets.QLabel(DialogParameters)
        self.lblRacine.setGeometry(QtCore.QRect(290, 190, 56, 16))
        self.lblRacine.setObjectName("lblRacine")

        self.retranslateUi(DialogParameters)
        QtCore.QMetaObject.connectSlotsByName(DialogParameters)

    def retranslateUi(self, DialogParameters):
        _translate = QtCore.QCoreApplication.translate
        DialogParameters.setWindowTitle(_translate("DialogParameters", "Gestion des classeurs"))
        self.lblTitre.setText(_translate("DialogParameters", "Gestion des paramètres"))
        self.btnRacine.setText(_translate("DialogParameters", "  Racine vidéo"))
        self.lblRacine.setText(_translate("DialogParameters", "TextLabel"))
