# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_sceneUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vuePrincipale = QtWidgets.QGraphicsView(self.centralwidget)
        self.vuePrincipale.setObjectName("vuePrincipale")
        self.verticalLayout.addWidget(self.vuePrincipale)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonChangerCouleur = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonChangerCouleur.setObjectName("pushButtonChangerCouleur")
        self.verticalLayout_2.addWidget(self.pushButtonChangerCouleur)
        self.pushButtonCreerDisque = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButtonCreerDisque.setObjectName("pushButtonCreerDisque")
        self.verticalLayout_2.addWidget(self.pushButtonCreerDisque)
        self.lineEditTexte = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEditTexte.setObjectName("lineEditTexte")
        self.verticalLayout_2.addWidget(self.lineEditTexte)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.vueGlobale = QtWidgets.QGraphicsView(self.dockWidgetContents)
        self.vueGlobale.setObjectName("vueGlobale")
        self.verticalLayout_2.addWidget(self.vueGlobale)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.dialRotation = QtWidgets.QDial(self.dockWidgetContents)
        self.dialRotation.setMinimum(-180)
        self.dialRotation.setMaximum(180)
        self.dialRotation.setProperty("value", -3)
        self.dialRotation.setWrapping(True)
        self.dialRotation.setNotchTarget(30.0)
        self.dialRotation.setNotchesVisible(True)
        self.dialRotation.setObjectName("dialRotation")
        self.verticalLayout_2.addWidget(self.dialRotation)
        self.horizontalSliderZoom = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSliderZoom.setMinimum(10)
        self.horizontalSliderZoom.setMaximum(10000)
        self.horizontalSliderZoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderZoom.setObjectName("horizontalSliderZoom")
        self.verticalLayout_2.addWidget(self.horizontalSliderZoom)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonChangerCouleur.setText(_translate("MainWindow", "Changer  couleur"))
        self.pushButtonCreerDisque.setText(_translate("MainWindow", "Créer disque"))
